travis:
  secure:
    BINSTAR_TOKEN: SR7nHkCkTHevidG+uw3/g4usUwDJQcYmxNOMVN/Oz3931kJl7wVsp8DfWY/RiX6grIZNvvSpcIHxyyUy3pLu02EfUKDLzaI+eKYKbO0WJryH3kRZiPhznm7OUUyGG+IMvkVZAlUyMeETjtCjt9tYs4+3A3hYJd0QIZxH9NeAu1sxYibGFmbIM5/FpMdTnmMuQDg7Bu1xcvKiq2K4lpe/jXcN27GZVVGZguBs4+94dlFSNH2j3e3bzzx6lUYUspVVVuQiq4oJMqvQ8Cha56Ban7LCoDpQ+CQ/Jn5jCpLwUxtYbZkRZM/tvqqj2HdUOsaNZ1Tt6Jg2nj/HkpOzOelmRiN7EIzviXEzfComBbO++emJ3rVXQ2zbgLAEYx28/560xNTaFYt5XQF1u1D6OrgptOXQHmhvOWz9CVG0m8Z1vwyR9VFtvJ9Ij4OuVmbWHoTicrpYEiJXKjMtuNCSysSw8bB0PVBJl4Yf1pY8HI2ENp+LxRs0oVJ1YL45Tvc/MCWe/uEvO+X6pUSijn1Bm66igFldiNeceSqcjGij/ZBAmzcj7dy+0uZICiuf+CYx91R5oi+OiuC5MZ1zQVo+iOgbbCRQNmaFrHEXAmiMlpUvGSmozsCJqTf2o/qw/MHx5Yb6TU2AmgdwkKWVM5df4d6RhWXYaXQ3WyTdvV4Lqr5lLCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
